routes.py
from flask import Flask, render_template, request, redirect,url_for, flash
from werkzeug.security import generate_password_hash
from datetime import datetime
from models import db, User, Book, Section, Mybooks, AccessRequests,Feedback
from flask import Blueprint

app = Blueprint('routes', __name__)

@app.route('/')
def welcome():
    quote = "Welcome to our library management system!"
    return render_template('welcome.html', quote=quote)

@app.route('/register',methods=['GET','POST'])
def register():
    if request.method == 'POST':   
        name=request.form.get('name')
        username=request.form.get('username')
        password=request.form.get('password')
        if username=='' or password=='' or name=='':
            flash('Above field(s) cannot be empty.')
            return redirect(url_for('routes.register'))
        if User.query.filter_by(username=username).first():
            flash('Username already exists.')
            return redirect(url_for('routes.register'))
        user=User(username=username,passhash=generate_password_hash(password),name=name)
        db.session.add(user)
        db.session.commit()
        flash('Username successfully registered.')
        return redirect(url_for('routes.login'))
    return render_template('register.html')

@app.route('/login',methods=['GET','POST'])
def login():
    if request.method == 'POST':
        username=request.form.get('username')
        password=request.form.get('password')
        if username=='' or password=='':
            flash('Above field(s) cannot be empty.')
        user=User.query.filter_by(username=username).first()
        if not user:
            flash('User does not exist, Kindly register.')
            return redirect(url_for('routes.register'))
        if not user.check_password(password):
            flash('Incorrect password.')
            return redirect(url_for('routes.login'))
        if user.is_admin:
            return redirect(url_for('routes.admin'))
        else:
            return redirect(url_for('routes.udash',id=user.id))
    return render_template('login.html')

@app.route('/admin')
def admin():
    return render_template('admin.html')

@app.route('/admin/sections')
def manage_sections():
    sections=Section.query.all()
    return render_template('asections.html',sections=sections)

@app.route('/admin/sections/add', methods=['GET','POST'])
def add_section():
    if request.method == 'POST':
        name=request.form.get('name')
        if not name:
            flash('Section cannot be empty.')
        if len(name)>64:
            flash('Section name cannot be greater than 64 characters.')
        else:
            sections=Section(name=name)
            db.session.add(sections)
            db.session.commit()
            flash('Section added successfully!')
            return redirect(url_for('routes.manage_sections'))
    return render_template('section/add.html')

@app.route('/admin/sections/view/<int:id>')
def view(id):
    section=Section.query.get(id)
    return render_template('section/view.html',section=section)

@app.route('/admin/sections/edit/<int:id>',methods=['GET','POST'])
def edit_section(id):
    sections=Section.query.get(id)
    if request.method == 'POST':
        name=request.form.get('name')
        if not name:
            flash('Section cannot be empty.')
        if len(name)>64:
            flash('Section name cannot be greater than 64 characters.')
        else:
            sections.name=name
            db.session.commit()
            flash('Section updated successfully!')
            return redirect(url_for('routes.manage_sections'))
    return render_template('section/edit.html',sections=sections)

@app.route('/admin/sections/delete/<int:id>',methods=['GET','POST'])
def delete_section(id):
    sections=Section.query.get(id)
    if request.method == 'POST':
        if sections:
            for book in sections.ebooks:
                db.session.delete(book)
            db.session.delete(sections)
            db.session.commit()
            flash('Section deleted successfully!')
            return redirect(url_for('routes.manage_sections'))
        else:
            flash('Section not found.')
            return redirect('routes.manage_sections')
    return render_template('section/delete.html',sections=sections)

@app.route('/admin/books')
def manage_books():
    books=Book.query.all()
    sections=Section.query.all()
    return render_template('abooks.html',books=books,sections=sections)

@app.route('/admin/books/add',methods=['GET','POST'])
def add_books():
    if request.method == 'POST':
        title=request.form.get('title')
        author=request.form.get('author')
        section_id=request.form.get('section')
        description=request.form.get('description')
        copies=request.form.get('copies')
        blink=request.form.get('blink')
        if not title or not author or not copies or blink:
            flash('Book cannot be empty.')
        if len(title)>64:
            flash('Book name cannot be greater than 64 characters.')
        book = Book(title=title, author=author, section_id=section_id, description=description, copies=copies,blink=blink)
        db.session.add(book)
        db.session.commit()
        flash('Book added successfully!')
        return redirect(url_for('routes.manage_books'))
    sections = Section.query.all()
    return render_template('book/add.html',sections=sections)

@app.route('/admin/books/edit/<id>',methods=['GET','POST'])
def edit_books(id):
    sections=Section.query.filter(id==id).all()
    books=Book.query.get(id)
    if request.method == 'POST':
        title=request.form.get('title')
        author=request.form.get('author')
        description=request.form.get('description')
        copies=request.form.get('copies')
        section_id = request.form.get('section')
        if not all([title,author,copies]):
            flash('Field(s) cannot be empty.')
        if len(title)>64 or len(author)>64:
            flash('Characters out of range.')
        else:
            copies=int(copies)
            section_id=int(section_id)
            books.title=title
            books.author=author
            books.description=description
            books.copies=copies
            books.section_id=section_id
            db.session.commit()
            flash('Book updated successfully!')
            return redirect(url_for('routes.manage_books'))
    return render_template('book/edit.html',books=books,sections=sections)

@app.route('/admin/books/delete/<int:id>',methods=['GET','POST'])
def delete_books(id):
    mybooks=Mybooks.query.filter_by(book_id=id).all()
    books=Book.query.get(id)
    if request.method == 'POST':
        if books:
            for mybook in mybooks:
                db.session.delete(mybook)
                db.session.commit()
            db.session.delete(books)
            db.session.commit()
            flash('Book deleted successfully!')
            return redirect(url_for('routes.manage_books'))
        else:
            flash('Books not found.')
            return redirect(url_for('routes.manage_books'))

    sections=Section.query.get(id)
    return render_template('book/delete.html',books=books,sections=sections)
                           
@app.route('/admin/manage_requests',methods=['GET','POST'])
def manage_requests():
    pending_requests = AccessRequests.query.filter_by(status='Pending').all()
    accepted_requests = AccessRequests.query.filter_by(status='Accepted').all()
    returned_requests = AccessRequests.query.filter_by(status='Returned').all()
    return render_template('manage_requests.html', requests=pending_requests, accepted_requests=accepted_requests,returned_requests=returned_requests)


@app.route('/admin/manage_requests/action/<int:request_id>/<action>')
def handle_request_action(request_id, action):
    access_request = AccessRequests.query.get(request_id)
    if access_request:
        user = User.query.filter_by(username=access_request.username).first()
        if action == 'grant':
            book=Book.query.get(access_request.book_id)
            print(book.id,book.title)
            book.copies-=1
            mybook = Mybooks(user_id=user.id,book_id=book.id,is_granted=True)
            db.session.add(mybook)
            access_request.status = 'Accepted'
            db.session.commit()
            flash('Access request is granted.')
        elif action =='reject':
            access_request.status = 'Rejected'
            db.session.commit()
            flash('Access request is rejected.')
        elif action =='revoke':
            book = Book.query.filter_by(title=access_request.ebook).first()
            user = User.query.filter_by(username=access_request.username).first()
            mybook = Mybooks.query.filter_by(user_id=user.id, book_id=book.id).first()
            if mybook.return_date<datetime.now():
                access_request.status = 'Revoked due to overdue'
                book.copies+=1
                revoked_book = Mybooks.query.filter_by(user_id=user.id, book_id=book.id).first()
                db.session.delete(revoked_book)
                db.session.commit()
                flash('Access request is automatically revoked.')
            else:
                access_request.status = 'Revoked'
                book.copies += 1
                revoked_book = Mybooks.query.filter_by(user_id=user.id, book_id=book.id).first()
                db.session.delete(revoked_book)
                db.session.commit()
                flash('Access request is manually revoked.')

    return redirect(url_for('routes.manage_requests'))

@app.route('/udash/<int:id>', methods=['GET', 'POST'])
def udash(id):
    user = User.query.get(id)
    my_books = Mybooks.query.filter_by(user_id=id).all()
    feedback = Feedback.query.filter(Feedback.user_id == id).all()
    if user and not user.is_admin:
        sections = Section.query.all()

templates/abooks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manage Books</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .sidebar {
            position: fixed;
            top: 0;
            left: 0;
            height: 100%;
            width: 250px;
            background-color: #343a40;
            padding-top: 20px;
        }
        .sidebar-item {
            color: #fff;
            padding: 10px 20px;
            border-bottom: 1px solid rgba(255, 255, 255, 0.1);
            }
        .container {
            padding: 30px;
            margin-left: 250px;
        }
        .table-container {
                margin-top: 20px;
            }
            .flask-message {
                text-align: center;
            }
      
    </style>
</head>
<body>
    <div class="flask-message">
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category =='error' %}
                <div class="alert alert-danger alter-dismissible fade show " role="alert">
                    {{ message }}
                </div>
            {% else %}
                <div  class="alert alert-success alter-dismissible fade show" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endwith %}
</div>
    <div class="sidebar">
        <h5 class="text-white text-center">Admin Dashboard</h5>
        <ul class="list-unstyled">
            <li class="sidebar-item"><a href="/admin/sections"style="color: #fff;">Manage Sections</a></li>
            <li class="sidebar-item"><a href="/admin/books"style="color: #fff;">Manage Books</a></li>
            <li class="sidebar-item"><a href="/admin/manage_requests"style="color: #fff;">Manage Requests</a></li>
            <li class="sidebar-item"><a href="/logout"style="color: #fff;">Logout</a></li>
        </ul>
    </div>
    <div class="container">
        <h2 class="mb-4">MANAGE BOOKS</h2>
        <a href="/admin/books/add" class="btn btn-primary mb-3">Add Book</a>
        
            <div class="table-container">
                <table class="table table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>Author</th>
                        <th>Date Created</th>
                        <th>Description</th>
                        <th>Copies</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for book in books %}
                        <tr>
                            <td>{{ book.id }}</td>
                            <td>{{ book.title }}</td>
                            <td>{{ book.author }}</td>
                            <td>{{ book.date_created }}</td>
                            <td>{{ book.description }}</td>
                            <td>{{ book.copies }}</td>
                            <td>
                                <a href="/admin/books/edit/{{ book.id }}" class="btn btn-sm btn-warning">Edit</a>
                                <a href="/admin/books/delete/{{ book.id }}" class="btn btn-sm btn-danger">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        
    </div>
</body>
</html>

templates/admin.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Library Management System - Admin Dashboard</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <style>
            .sidebar {
                position: fixed;
                top: 0;
                left: 0;
                height: 100%;
                width: 250px;
                background-color: #343a40;
                padding-top: 20px;
            }
            .sidebar-item {
                color: #fff;
                padding: 10px 20px;
                border-bottom: 1px solid rgba(255, 255, 255, 0.1);
            }
            .main-content {
                margin-left: 250px;
                padding: 20px;
            }
        </style>
    </head>
    <body>
        <div class="sidebar">
            <h4 class="text-white text-center">Admin Dashboard</h4>
            <nav>
                <ul class="list-unstyled">
                    <li class="sidebar-item"><a href="/admin/sections" style="color: #fff;">Manage Sections</a></li>
                    <li class="sidebar-item"><a href="/admin/books" style="color: #fff;">Manage Books</a></li>
                    <li class="sidebar-item"><a href="/admin/manage_requests" style="color: #fff;">Manage Requests</a></li>
                    <li class="sidebar-item"><a href="/logout" style="color: #fff;">Logout</a></li>
                </ul>
            </nav>
        </div>
        <div class="main-content">
            <b><u><h2 style="color: red;">Welcome to the Library Management System Admin Dashboard</h2></u></b>
            <p style="font-size:22px ;">This is where you can manage sections, books, view statistics, and perform administrative tasks.</p>
        </div>
    </body>
</html>

templates/asections.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Library Management System - Admin Dashboard</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <style>
            .sidebar {
                position: fixed;
                top: 0;
                left: 0;
                height: 100%;
                width: 250px;
                background-color: #343a40;
                padding-top: 20px;
            }
            .sidebar-item {
                color: #fff;
                padding: 10px 20px;
                border-bottom: 1px solid rgba(255, 255, 255, 0.1);
            }
            .container {
                padding: 20px;
                margin-left: 250px;
            }
            .table-container {
                margin-top: 20px;
            }
            .flask-message {
                text-align: center;
            }
      
        </style>
    </head>
    <body>
        <div class="flask-message">
        {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category =='error' %}
                <div class="alert alert-danger alter-dismissible fade show " role="alert">
                    {{ message }}
                </div>
            {% else %}
                <div  class="alert alert-success alter-dismissible fade show" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endwith %}
</div>
        <div class="sidebar">
            <h5 class="text-white text-center">Admin Dashboard</h5>
            <ul class="list-unstyled">
                <li class="sidebar-item"><a href="/admin/sections" style="color: #fff;">Manage Sections</a></li>
                <li class="sidebar-item"><a href="/admin/books" style="color: #fff;">Manage Books</a></li>
                <li class="sidebar-item"><a href="/admin/manage_requests" style="color: #fff;">Manage Requests</a></li>
                <li class="sidebar-item"><a href="/logout" style="color: #fff;">Logout</a></li>
            </ul>
        </div>
        <div class="container">
            <h2>MANAGE SECTIONS</h2><br>
            <a href="/admin/sections/add" class="btn btn-primary mb-3">Add Section</a>
            <div class="table-container">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Section ID</th>
                            <th>Section Name</th>
                            <th>Number of books</th>
                            <th>Section created</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                {% for section in sections %}
                        <tr> 
                            <td>{{section.id}}</td>
                            <td>{{section.name}}</td>  
                            <td>{{section.ebooks|length}}</td>
                            <td>{{section.date_created}}</td>
                            <td>
                                <a href="/admin/sections/view/{{ section.id }}" class="btn btn-sm btn-warning">View</a>
                                <a href="/admin/sections/edit/{{ section.id }}" class="btn btn-sm btn-primary">Edit</a>
                                <a href="/admin/sections/delete/{{ section.id }}" class="btn btn-sm btn-danger">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </body>
</html>

templates/feedback.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <title>Book Feedback</title>
    <style>
        .container{
            margin-left: 60px;
            margin-top: 20px;
        }
        .flask-message {
                text-align: center;
            }
      
    </style>
</head>
<body>
    <div class="flask-message">
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category =='error' %}
                <div class="alert alert-danger alter-dismissible fade show " role="alert">
                    {{ message }}
                </div>
            {% else %}
                <div  class="alert alert-success alter-dismissible fade show" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endwith %}
</div>

    <div class="container">
    <br><u><h2 style="color: red;">Book Feedback Form</h2></u><br>
    <form action="{{ url_for('routes.give_feedback',book_id=book_id,user_id=user_id) }}" method="post">
        <label for="feedback" style="font-size: 20px;">Feedback:</label><br>
        <input type="hidden" name="user_id" value="{{ user_id }}">
        <input type="hidden" name="book_id" value="{{ book_id}}">
        <textarea id="feedback" name="feedback" rows="5" cols="50" placeholder="Enter your thoughts here."></textarea><br><br>
        <button type="submit" class="btn btn-success" value="Submit">Submit</button>
    </form>
    </div>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang = "en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport", content="width=device-width,initial-scale=1.0">
        <title>LOGIN FORM</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <style>
            body {
                background-color: #f8f9fa;
            }
            .login-container {
                max-width: 400px;
                margin: 100px auto;
                padding: 30px;
                background-color: #fff;
                border-radius: 10px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            }
            .login-container h2 {
                text-align: center;
                margin-bottom: 30px;
            }
            .form-group {
                margin-bottom: 20px;
            }
            .form-control {
                height: 50px;
                border-radius: 25px;
                padding: 10px 20px;
            }
            .btn-login {
                border-radius: 25px;
                padding: 10px 20px;
            }
            .flask-message {
                text-align: center;
            }
      
        </style>
    </head>
    <body>
        <div class="flask-message">
        {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category =='error' %}
                <div class="alert alert-danger alter-dismissible fade show " role="alert">
                    {{ message }}
                </div>
            {% else %}
                <div  class="alert alert-success alter-dismissible fade show" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endwith %}
        </div>
           
        <div class="login-container">
            <u><h2>Login</h2></u>
            <form action="/login" method="post">
                <div class="form-group">
                    <input type="text" class="form-control" name="username" id="username" placeholder="Username" required>
                </div> 
                <div class="form-group">
                    <input type="password" class="form-control" name="password" id="password" placeholder="Password" required>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block btn-login">Login</button>
                </div>
            </form>
            <p class="text-center">Don't have an account? <a href="/register">Sign up</a></p>
        </div>
    </body>
</html>

templates/manage_requests.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manage Requests</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <style>
            .sidebar {
                position: fixed;
                top: 0;
                left: 0;
                height: 100%;
                width: 250px;
                background-color: #343a40;
                padding-top: 20px;
            }
            .sidebar-item {
                color: #fff;
                padding: 10px 20px;
                border-bottom: 1px solid rgba(255, 255, 255, 0.1);
            }
            .container {
                padding: 20px;
                margin-left: 250px;
            }
            .table-container {
                margin-top: 20px;
            }
            .flask-message {
                text-align: center;
            }
      
        </style>
</head>
<body>
    <div class="flask-message">
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category =='error' %}
                <div class="alert alert-danger alter-dismissible fade show " role="alert">
                    {{ message }}
                </div>
            {% else %}
                <div  class="alert alert-success alter-dismissible fade show" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endwith %}
</div>
    <div class="sidebar">
        <h5 class="text-white text-center">Admin Dashboard</h5>
        <nav>
            <ul class="list-unstyled">
                <li class="sidebar-item"><a href="/admin/sections"style="color: #fff;">Manage Sections</a></li>
                <li class="sidebar-item"><a href="/admin/books"style="color: #fff;">Manage Books</a></li>
                <li class="sidebar-item"><a href="/admin/manage_requests"style="color: #fff;">Manage Requests</a></li>
                <li class="sidebar-item"><a href="/logout"style="color: #fff;">Logout</a></li>
            </ul>
        </nav>
    </div>
    <div class="container">
        <h3>MANAGE REQUESTS</h3>
        <div class="table-container">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Username</th>
                        <th>Book Title</th>
                        <th>Request Date</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for request in requests %}
                    <tr>
                        <td>{{ request.username }}</td>
                        <td>{{ request.ebook }}</td>
                        <td>{{ request.request_date }}</td>
                            <td class="d-flex justify-content-between">
                            {% if request.status == 'Pending' %}
                            <div class="d-flex" style="gap: 10px;">
                            <form action="{{ url_for('routes.handle_request_action', request_id=request.id, action='grant') }}" method="GET">
                                <input type="hidden" name="username" value="{{ request.username }}">
                                <input type="hidden" name="ebook" value="{{ request.ebook }}">
                                <button type="submit" class="btn btn-sm btn-primary">Grant</button>
                            </form>
                            <form action="{{ url_for('routes.handle_request_action', request_id=request.id, action='reject') }}" method="GET">
                                <input type="hidden" name="username" value="{{ request.username }}">
                                <input type="hidden" name="ebook" value="{{ request.ebook }}">
                                <button type="submit" class="btn btn-sm btn-danger">Reject</button>
                            </form>
                            </div>
                        {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    
            <div class="container">
            <h3>ACCEPTED REQUESTS</h3>
            <div class="table-container">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Username</th>
                            <th>Book Title</th>
                            <th>Request Date</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for request in accepted_requests %}
                        <tr>
                            <td>{{ request.username }}</td>
                            <td>{{ request.ebook }}</td>
                            <td>{{ request.request_date }}</td>
                            <td>
                                <form action="{{ url_for('routes.handle_request_action', request_id=request.id, action='revoke') }}" method="GET">
                                    <input type="hidden" name="username" value="{{ request.username }}">
                                    <input type="hidden" name="ebook" value="{{ request.ebook }}">
                                    <button type="submit" class="btn btn-sm btn-warning" >Revoke</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
                </div>
            </div>
                <div class="container">
                    <h3>RETURNED REQUESTS</h3>
                    <div class="table-container">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Username</th>
                                    <th>Book Title</th>
                                    <th>Request Date</th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                            {% for request in returned_requests %}
                                <tr>
                                    <td>{{ request.username }}</td>
                                    <td>{{ request.ebook }}</td>
                                    <td>{{ request.request_date }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>